apiVersion: v1
kind: Service
metadata:
  name: gowebserver-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: webserver-port
    protocol: TCP
  selector:
    app: gowebserver
  type: NodePort
